import type { Suggestion } from './types';

export const commands = {
  getSuggestions: 'GET_SUGGESTIONS',
  switchTab: 'SWITCH_TAB',
  newTab: 'NEW_TAB',
  clearHistory: 'CLEAR_HISTORY',
  bookmarkCurrentTab: 'BOOKMARK_CURRENT_TAB',
  pinCurrentTab: 'PIN_CURRENT_TAB',
  muteCurrentTab: 'MUTE_CURRENT_TAB',
  reloadCurrentTab: 'RELOAD_CURRENT_TAB',
  fullscreenCurrentTab: 'FULLSCREEN_CURRENT_TAB',
  printCurrentTab: 'PRINT_CURRENT_TAB',
  closeCurrentTab: 'CLOSE_CURRENT_TAB',
  duplicateCurrentTab: 'DUPLICATE_CURRENT_TAB',
  openIncognitoWindow: 'OPEN_INCOGNITO_WINDOW',
};

export const actions: Suggestion[] = [
  {
    content: 'https://docs.new',
    description: 'Create a new Google Docs document',
    type: 'action',
    iconUrl: chrome.runtime.getURL('/assets/docs.png'),
  },
  {
    content: 'https://slides.new',
    description: 'Create a new Google Slides presentation',
    type: 'action',
    iconUrl: chrome.runtime.getURL('/assets/slides.png'),
  },
  {
    content: 'https://sheets.new',
    description: 'Create a new Google Sheets spreadsheet',
    type: 'action',
    iconUrl: chrome.runtime.getURL('/assets/sheets.png'),
  },
  {
    content: 'https://meet.new',
    description: 'Start a new Google Meet',
    type: 'action',
    iconUrl: chrome.runtime.getURL('/assets/meet.png'),
  },
  {
    content: 'https://www.notion.so/new',
    description: 'Create a new Notion page',
    type: 'action',
    iconUrl: chrome.runtime.getURL('/assets/notion.png'),
  },
  {
    content: 'https://github.com/new',
    description: 'Create a new GitHub repository',
    type: 'action',
    iconUrl: chrome.runtime.getURL('/assets/github.svg'),
  },
  {
    content: 'https://text2audio.cc',
    description: 'Generate audio from text',
    type: 'action',
    iconUrl: chrome.runtime.getURL('/assets/text2audio.ico'),
  },
  {
    content: 'https://trello.com/create-board',
    description: 'Create new Trello board',
    type: 'action',
    iconUrl: chrome.runtime.getURL('/assets/trello.png'),
  },
  {
    content: 'https://figma.new',
    description: 'Create a new Figma design file',
    type: 'action',
    iconUrl: chrome.runtime.getURL('/assets/figma.png'),
  },
  {
    content: 'https://codepen.io/pen/',
    description: 'Create a new CodePen',
    type: 'action',
    iconUrl: chrome.runtime.getURL('/assets/codepen.ico'),
  },
  {
    content: 'bookmark_current_tab',
    description: 'Bookmark current tab',
    type: 'action',
    iconUrl: 'Bookmark',
    action: () => chrome.runtime.sendMessage({ type: commands.bookmarkCurrentTab }),
  },
  {
    content: 'pin_current_tab',
    description: 'Pin/Unpin current tab',
    type: 'action',
    iconUrl: 'Pin',
    action: () => chrome.runtime.sendMessage({ type: commands.pinCurrentTab }),
  },
  {
    content: 'mute_current_tab',
    description: 'Mute/Unmute current tab',
    type: 'action',
    iconUrl: 'Mute',
    action: () => chrome.runtime.sendMessage({ type: commands.muteCurrentTab }),
  },
  {
    content: 'reload_current_tab',
    description: 'Reload current tab',
    type: 'action',
    iconUrl: 'Reload',
    action: () => chrome.runtime.sendMessage({ type: commands.reloadCurrentTab }),
  },
  {
    content: 'fullscreen_current_tab',
    description: 'Toggle fullscreen for current tab',
    type: 'action',
    iconUrl: 'Fullscreen',
    action: () => chrome.runtime.sendMessage({ type: commands.fullscreenCurrentTab }),
  },
  {
    content: 'print_current_tab',
    description: 'Print current tab',
    type: 'action',
    iconUrl: 'Print',
    action: () => chrome.runtime.sendMessage({ type: commands.printCurrentTab }),
  },
  {
    content: 'close_current_tab',
    description: 'Close current tab',
    type: 'action',
    iconUrl: 'Close',
    action: () => chrome.runtime.sendMessage({ type: commands.closeCurrentTab }),
  },
  {
    content: 'duplicate_current_tab',
    description: 'Duplicate current tab',
    type: 'action',
    iconUrl: 'Duplicate',
    action: () => chrome.runtime.sendMessage({ type: commands.duplicateCurrentTab }),
  },
  {
    content: 'open_incognito_window',
    description: 'Open new incognito window',
    type: 'action',
    iconUrl: 'Incognito',
    action: () => chrome.runtime.sendMessage({ type: commands.openIncognitoWindow }),
  },
];
